Phone Directory/Phone Directory/Models/Directory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Phone_Directory.Models
{
    public class Directory
    {
        [Key]
        public int UID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1, 999, ErrorMessage = "ISD Code must not be more than 3 digits.")]
        public int ISD { get; set; }

        [Required]
        [Range(1, 9999999999, ErrorMessage = "Contact number must be of 10 digits.")]
        public int Number { get; set; }



    }
}

Phone Directory/Phone Directory/Models/ErrorViewModel.cs
using System;

namespace Phone_Directory.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Phone Directory/Phone Directory/Controllers/DirectoryController.cs
using Microsoft.AspNetCore.Mvc;
using Phone_Directory.Data;
using Phone_Directory.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Phone_Directory.Controllers
{
    public class DirectoryController : Controller
    {

        private readonly ApplicationDbContext _db;

        public DirectoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Directory> objlist = _db.Directory;
            return View(objlist);
        }

        //GET CREATE
        public IActionResult Create()
        {

            return View();
        }

        //POST CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Directory obj)
        {
            if (ModelState.IsValid)
            {
                _db.Directory.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();

        }

        //GET EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Directory.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Directory obj)
        {
            if (ModelState.IsValid)
            {
                _db.Directory.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();

        }

        //GET DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Directory.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteP(Directory obj)
        {

            if (obj == null)
            {
                return NotFound();
            }
            _db.Directory.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

Phone Directory/Phone Directory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Phone_Directory.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Phone_Directory.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Phone Directory/Phone Directory/Views/Directory/Create.cshtml
@model Phone_Directory.Models.Directory

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Contact Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        ISD Code
                    </div>
                    <div class="col-8">
                        <input asp-for="ISD" class="form-control" />
                        <span asp-validation-for="ISD" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        Contact Number
                    </div>
                    <div class="col-8">
                        <input asp-for="Number" class="form-control" />
                        <span asp-validation-for="Number" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>

        </div>
    </div>
</form>
@section scripts
{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Phone Directory/Phone Directory/Views/Directory/Delete.cshtml
@model Phone_Directory.Models.Directory

<form method="post" asp-action="DeleteP">
    <input asp-for="UID" hidden />
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Contact Detail</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        ISD Code
                    </div>
                    <div class="col-8">
                        <input asp-for="ISD" disabled class="form-control" />
                        <span asp-validation-for="ISD" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        Contact Number
                    </div>
                    <div class="col-8">
                        <input asp-for="Number" disabled class="form-control" />
                        <span asp-validation-for="Number" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info  w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>

        </div>
    </div>
</form>
@section scripts
{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Phone Directory/Phone Directory/Views/Directory/Edit.cshtml
@model Phone_Directory.Models.Directory

<form method="post" asp-action="Edit">
    <input asp-for="UID" hidden />
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Contact Detail</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        ISD Code
                    </div>
                    <div class="col-8">
                        <input asp-for="ISD" class="form-control" />
                        <span asp-validation-for="ISD" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        Contact Number
                    </div>
                    <div class="col-8">
                        <input asp-for="Number" class="form-control" />
                        <span asp-validation-for="Number" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>

        </div>
    </div>
</form>
@section scripts
{

    @{
<partial name="_ValidationScriptsPartial" />
    }
}

Phone Directory/Phone Directory/Views/Directory/Index.cshtml
@model IEnumerable<Phone_Directory.Models.Directory>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Phone Directory</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Directory" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New Contact
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        <center>Contact Name</center>
                    </th>
                    <th>
                        <center>ISD Code</center>
                    </th>
                    <th>
                        <center>Contact Number</center>
                    </th>
                    <th>
                        <center>Updation</center>
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="30%">@obj.Name</td>
                    <td width="10%">@obj.ISD</td>
                    <td width="30%">@obj.Number</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Directory" asp-route-Id="@obj.UID" asp-action="Edit" class="btn btn-primary ">
                                <i class="fas fa-edit"></i>Edit
                            </a>
                            <a asp-controller="Directory" asp-route-Id="@obj.UID" asp-action="Delete" class="btn btn-danger">
                                <i class="far fa-trash-alt"></i>Delete
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No category exists.</p>
    }

</div>

Phone Directory/Phone Directory/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">This is a Phone Directory</h1>
   
</div>

Phone Directory/Phone Directory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  Phone Directory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MASTER RAW</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Directory" asp-action="Index">Directory</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>